
development:
  pepipost_api_key: "4cef6b7a599bc660d4d448e3faad4c66"
  pepipost_url: "https://api.pepipost.com/v2/sendEmail"

production:
  pepipost_api_key: "4cef6b7a599bc660d4d448e3faad4c66"
  pepipost_url: "https://api.pepipost.com/v2/sendEmail"